/// B2B 种子商品数据
///
/// 覆盖多个行业，用于发现页 MVP 展示和推荐匹配。
/// TODO：后续接入真实商品 API 或商家入驻。
library;

import 'product_model.dart';

/// 种子商品列表
const List<Product> kSeedProducts = [
  // === 软件开发 / IT 服务 ===
  Product(
    id: 'it001',
    title: '企业级软件开发外包 · 定制化管理系统',
    description:
        '专注企业管理系统定制开发：ERP、CRM、OA、WMS 仓储管理系统。10年开发经验团队，支持需求调研、原型设计、开发、测试、上线全流程。提供源代码交付和一年免费维护。',
    type: ProductType.service,
    priceMin: 50000,
    priceMax: 500000,
    priceUnit: '/项目',
    moq: '1个项目起',
    location: '四川成都',
    supplierName: '成都风腾伟业科技',
    supplierRating: 92,
    certified: true,
    industryTags: ['软件', 'IT服务', '企业服务'],
    keywords: ['软件开发', 'ERP', 'CRM', 'OA', '定制开发', '管理系统'],
    dealCount: 156,
    listedAt: 1700000000000,
  ),
  Product(
    id: 'it002',
    title: 'AI 智能客服系统 · 私有化部署',
    description:
        '基于大语言模型的智能客服系统，支持私有化部署。自动回复率达85%，支持多渠道接入（网页、APP、微信）。提供知识库训练、工单系统、数据分析报表。',
    type: ProductType.service,
    priceMin: 30000,
    priceMax: 80000,
    priceUnit: '/套',
    moq: '1套起',
    location: '四川成都',
    supplierName: '智联科技',
    supplierRating: 88,
    certified: true,
    industryTags: ['软件', 'AI', '企业服务'],
    keywords: ['AI客服', '智能客服', '大模型', '私有化部署', '客服系统'],
    dealCount: 89,
    listedAt: 1705000000000,
  ),
  Product(
    id: 'it003',
    title: '小程序开发 · 电商/门店/预约',
    description:
        '微信小程序定制开发：电商商城、门店预约、外卖点餐、会员系统。7天快速上线，提供运营指导和技术支持。已有200+成功案例。',
    type: ProductType.service,
    priceMin: 8000,
    priceMax: 30000,
    priceUnit: '/个',
    moq: '1个起',
    location: '四川成都',
    supplierName: '开始送科技',
    supplierRating: 85,
    certified: false,
    industryTags: ['软件', 'IT服务'],
    keywords: ['小程序', '微信小程序', '电商', '商城', '门店系统'],
    dealCount: 234,
    listedAt: 1710000000000,
  ),

  // === 供应链 / 物流 ===
  Product(
    id: 'sc001',
    title: '全国干线物流运输 · 整车/零担',
    description:
        '覆盖全国300+城市的干线物流服务，整车和零担均可。自有车队200+辆，提供门到门服务。价格透明，全程GPS跟踪，货物保险全覆盖。',
    type: ProductType.service,
    priceMin: 500,
    priceMax: 50000,
    priceUnit: '/趟',
    moq: '1趟起',
    location: '四川成都',
    supplierName: '西部铭仁供应链',
    supplierRating: 95,
    certified: true,
    industryTags: ['供应链', '物流', '运输'],
    keywords: ['物流', '运输', '整车', '零担', '干线运输', '货运'],
    dealCount: 567,
    listedAt: 1695000000000,
  ),
  Product(
    id: 'sc002',
    title: '仓储管理服务 · 成都本地仓库',
    description:
        '成都高新区标准仓库出租，面积100-5000㎡可选。提供仓储管理、分拣打包、库存盘点、代发货一站式服务。WMS系统对接，库存实时可视化。',
    type: ProductType.service,
    priceMin: 25,
    priceMax: 45,
    priceUnit: '/㎡/月',
    moq: '100㎡起',
    location: '四川成都高新区',
    supplierName: '西部铭仁供应链',
    supplierRating: 90,
    certified: true,
    industryTags: ['供应链', '仓储', '物流'],
    keywords: ['仓库', '仓储', '代管仓', '云仓', '库存管理'],
    dealCount: 78,
    listedAt: 1702000000000,
  ),
  Product(
    id: 'sc003',
    title: '供应链金融服务 · 应收账款融资',
    description:
        '为中小企业提供供应链金融服务：应收账款融资、订单融资、仓单质押。审批快（3个工作日），额度最高500万，利率优惠。',
    type: ProductType.service,
    priceMin: 100000,
    priceMax: 5000000,
    priceUnit: '/额度',
    moq: '10万起',
    location: '四川成都',
    supplierName: '西部铭仁供应链',
    supplierRating: 87,
    certified: true,
    industryTags: ['供应链', '金融'],
    keywords: ['供应链金融', '融资', '应收账款', '贷款', '企业融资'],
    dealCount: 45,
    listedAt: 1708000000000,
  ),

  // === 能源 / 充电 ===
  Product(
    id: 'en001',
    title: '充电桩安装运营 · 场站建设',
    description:
        '新能源汽车充电桩一站式解决方案：场站规划、设备采购、安装施工、运营维护。直流/交流桩全系列，支持加盟合作。已在四川地区建设50+充电站。',
    type: ProductType.service,
    priceMin: 50000,
    priceMax: 500000,
    priceUnit: '/站',
    moq: '1站起',
    location: '四川成都',
    supplierName: '西部铭仁能源',
    supplierRating: 91,
    certified: true,
    industryTags: ['新能源', '充电', '能源'],
    keywords: ['充电桩', '充电站', '新能源', '电动汽车', '充电设施'],
    dealCount: 67,
    listedAt: 1712000000000,
  ),
  Product(
    id: 'en002',
    title: '光伏电站建设 · 企业屋顶分布式',
    description:
        '企业屋顶分布式光伏电站建设：勘察设计、设备供应、安装施工、并网验收全流程。25年质保，投资回报期5-7年。已服务100+企业客户。',
    type: ProductType.service,
    priceMin: 100000,
    priceMax: 2000000,
    priceUnit: '/项目',
    moq: '100㎡屋顶',
    location: '四川成都',
    supplierName: '西部铭仁能源',
    supplierRating: 93,
    certified: true,
    industryTags: ['新能源', '光伏', '能源'],
    keywords: ['光伏', '太阳能', '分布式光伏', '屋顶发电', '绿色能源'],
    dealCount: 34,
    listedAt: 1715000000000,
  ),
  Product(
    id: 'en003',
    title: '储能系统设备 · 工商业储能',
    description:
        '工商业储能系统设备供应：50kWh-2MWh全系列，支持峰谷套利、需量管理、备用电源。液冷/风冷可选，寿命10年+。提供安装调试和运维服务。',
    type: ProductType.physical,
    priceMin: 80000,
    priceMax: 800000,
    priceUnit: '/套',
    moq: '1套起',
    location: '广东深圳',
    supplierName: '蓝海储能科技',
    supplierRating: 86,
    certified: true,
    industryTags: ['新能源', '储能', '能源'],
    keywords: ['储能', '储能系统', '工商业储能', '电池储能', '峰谷套利'],
    dealCount: 52,
    listedAt: 1718000000000,
  ),

  // === 包装 / 原材料 ===
  Product(
    id: 'pk001',
    title: '定制包装 · 纸箱/礼盒/彩盒',
    description:
        '专业包装定制：瓦楞纸箱、礼品盒、彩盒、手提袋。提供设计、印刷、模切、成型一站式服务。起订量低，500个起订，7-10天交货。',
    type: ProductType.physical,
    priceMin: 1.5,
    priceMax: 15,
    priceUnit: '/个',
    moq: '500个起',
    location: '广东东莞',
    supplierName: '恒丰包装制品',
    supplierRating: 89,
    certified: true,
    industryTags: ['包装', '印刷', '原材料'],
    keywords: ['纸箱', '礼盒', '彩盒', '包装定制', '印刷包装'],
    dealCount: 345,
    listedAt: 1698000000000,
  ),
  Product(
    id: 'pk002',
    title: '塑料原料 · PP/PE/PET 颗粒',
    description:
        '主营PP、PE、PET等塑料原料颗粒，厂家直供。全新料/再生料可选，量大价优。支持小批量试样，提供COA和物性表。',
    type: ProductType.physical,
    priceMin: 7.5,
    priceMax: 12.8,
    priceUnit: '/kg',
    moq: '25kg起',
    location: '浙江宁波',
    supplierName: '华塑新材料',
    supplierRating: 94,
    certified: true,
    industryTags: ['原材料', '塑料', '化工'],
    keywords: ['塑料颗粒', 'PP', 'PE', 'PET', '原料', '塑料原料'],
    dealCount: 892,
    listedAt: 1690000000000,
  ),
  Product(
    id: 'pk003',
    title: '不干胶标签定制 · 各类材质',
    description:
        '不干胶标签定制印刷：铜版纸、PET、PVC、热敏纸等各类材质。支持彩色印刷、烫金、模切。适合食品、日化、电子产品标签。',
    type: ProductType.physical,
    priceMin: 0.05,
    priceMax: 0.5,
    priceUnit: '/张',
    moq: '5000张起',
    location: '四川成都',
    supplierName: '天府印务',
    supplierRating: 83,
    certified: false,
    industryTags: ['包装', '印刷'],
    keywords: ['标签', '不干胶', '贴纸', '标签印刷', '条码标签'],
    dealCount: 267,
    listedAt: 1706000000000,
  ),

  // === 食品 / 农产品 ===
  Product(
    id: 'fd001',
    title: '四川特产 · 花椒/辣椒/火锅底料',
    description:
        '正宗四川汉源花椒、二荆条辣椒、手工火锅底料。原产地直采，无中间商。支持贴牌代工，OEM/ODM均可。提供食品检测报告。',
    type: ProductType.physical,
    priceMin: 25,
    priceMax: 180,
    priceUnit: '/kg',
    moq: '10kg起',
    location: '四川成都',
    supplierName: '川味源食品',
    supplierRating: 96,
    certified: true,
    industryTags: ['食品', '农产品', '调味品'],
    keywords: ['花椒', '辣椒', '火锅底料', '调味品', '四川特产', '川味'],
    dealCount: 1234,
    listedAt: 1685000000000,
  ),
  Product(
    id: 'fd002',
    title: '有机农产品 · 蔬菜/水果基地直供',
    description:
        '有机蔬菜、时令水果基地直供。成都周边300亩种植基地，当日采摘当日配送。支持企业食堂、餐饮连锁、社区团购供货。',
    type: ProductType.physical,
    priceMin: 3,
    priceMax: 25,
    priceUnit: '/kg',
    moq: '50kg起',
    location: '四川成都',
    supplierName: '绿源农业',
    supplierRating: 90,
    certified: true,
    industryTags: ['食品', '农产品'],
    keywords: ['蔬菜', '水果', '有机', '农产品', '基地直供', '生鲜'],
    dealCount: 456,
    listedAt: 1701000000000,
  ),
  Product(
    id: 'fd003',
    title: '食品代工 OEM/ODM · 休闲零食',
    description:
        '休闲零食代加工：坚果炒货、糕点饼干、肉制品。SC认证工厂，10万级净化车间。支持配方研发、包装设计、生产全流程。',
    type: ProductType.service,
    priceMin: 0.5,
    priceMax: 5,
    priceUnit: '/件',
    moq: '5000件起',
    location: '四川成都',
    supplierName: '美味多食品',
    supplierRating: 88,
    certified: true,
    industryTags: ['食品', '代工'],
    keywords: ['食品代工', 'OEM', 'ODM', '零食代工', '休闲食品', '代加工'],
    dealCount: 78,
    listedAt: 1709000000000,
  ),

  // === 办公 / 企业服务 ===
  Product(
    id: 'sv001',
    title: '企业财税代理记账 · 小规模/一般纳税人',
    description:
        '专业代理记账服务：小规模纳税人200元/月起，一般纳税人500元/月起。包含记账、报税、年报、发票管理。注册会计师团队服务。',
    type: ProductType.service,
    priceMin: 200,
    priceMax: 800,
    priceUnit: '/月',
    moq: '1年起',
    location: '四川成都',
    supplierName: '精财财税',
    supplierRating: 92,
    certified: true,
    industryTags: ['企业服务', '财税'],
    keywords: ['代理记账', '财税', '报税', '公司注册', '财务外包'],
    dealCount: 567,
    listedAt: 1697000000000,
  ),
  Product(
    id: 'sv002',
    title: '企业法律顾问 · 常年法务咨询',
    description:
        '常年法律顾问服务：合同审查、法律咨询、劳动纠纷、知识产权保护。律师团队服务，响应时间4小时内。适合中小企业常年法务需求。',
    type: ProductType.service,
    priceMin: 5000,
    priceMax: 30000,
    priceUnit: '/年',
    moq: '1年起',
    location: '四川成都',
    supplierName: '明伦律师事务所',
    supplierRating: 95,
    certified: true,
    industryTags: ['企业服务', '法律'],
    keywords: ['法律顾问', '律师', '合同审查', '法务', '法律咨询'],
    dealCount: 123,
    listedAt: 1703000000000,
  ),
  Product(
    id: 'sv003',
    title: '企业培训 · 团队建设/管理培训',
    description:
        '企业内训服务：团队建设、销售技巧、管理能力、新员工入职培训。资深讲师团队，定制化课程方案。线上+线下结合。',
    type: ProductType.service,
    priceMin: 3000,
    priceMax: 50000,
    priceUnit: '/天',
    moq: '1天起',
    location: '四川成都',
    supplierName: '知行培训',
    supplierRating: 85,
    certified: false,
    industryTags: ['企业服务', '培训'],
    keywords: ['企业培训', '内训', '团队建设', '管理培训', '员工培训'],
    dealCount: 89,
    listedAt: 1711000000000,
  ),

  // === 电子 / 元器件 ===
  Product(
    id: 'el001',
    title: '电子元器件 ·  resistors/capacitors/IC',
    description:
        '主营各类电子元器件：电阻、电容、二极管、三极管、IC芯片。原装正品，深圳华强北货源，当天发货。支持BOM配单服务。',
    type: ProductType.physical,
    priceMin: 0.01,
    priceMax: 100,
    priceUnit: '/个',
    moq: '100个起',
    location: '广东深圳',
    supplierName: '华强电子',
    supplierRating: 93,
    certified: true,
    industryTags: ['电子', '元器件'],
    keywords: ['电子元器件', '电阻', '电容', 'IC', '芯片', 'BOM配单'],
    dealCount: 2345,
    listedAt: 1680000000000,
  ),
  Product(
    id: 'el002',
    title: '智能硬件代工 · IoT设备方案',
    description:
        '智能硬件ODM/OEM：IoT设备、智能家居、可穿戴设备。提供方案设计、PCB开发、结构设计、PCBA贴片、整机组装全流程。',
    type: ProductType.service,
    priceMin: 50000,
    priceMax: 500000,
    priceUnit: '/项目',
    moq: '1000台起',
    location: '广东深圳',
    supplierName: '智联硬件',
    supplierRating: 87,
    certified: true,
    industryTags: ['电子', '智能硬件', 'IoT'],
    keywords: ['智能硬件', 'IoT', 'ODM', 'OEM', 'PCBA', '硬件开发'],
    dealCount: 45,
    listedAt: 1716000000000,
  ),
];
